
(define (problem planificator)
    (:domain planificator3000)
    (:objects 
        p1 p2 p3 p4 p5 p6     - programador
        t1 t2 t3 t4 t5 t6 t7 t8 t9 t10 t11 t12    - tasca
    )
    (:init

        (disponible p1)
        (disponible p2)
        (disponible p3)
        (disponible p4)
        (disponible p5)
        (disponible p6)

        (= (habilitat p1) 1)
        (= (habilitat p2) 2)
        (= (habilitat p3) 2)
        (= (habilitat p4) 3)
        (= (habilitat p5) 2)
        (= (habilitat p6) 3)

        (= (calitat p1) 1)
        (= (calitat p2) 1)
        (= (calitat p3) 2)
        (= (calitat p4) 1)
        (= (calitat p5) 2)
        (= (calitat p6) 1)

        (not (asignada t1))
        (not (asignada t2))
        (not (asignada t3))
        (not (asignada t4))
        (not (asignada t5))
        (not (asignada t6))
        (not (asignada t7))
        (not (asignada t8))
        (not (asignada t9))
        (not (asignada t10))
        (not (asignada t11))
        (not (asignada t12))

        (not (revisada t1))
        (not (revisada t2))
        (not (revisada t3))
        (not (revisada t4))
        (not (revisada t5))
        (not (revisada t6))
        (not (revisada t7))
        (not (revisada t8))
        (not (revisada t9))
        (not (revisada t10))
        (not (revisada t11))
        (not (revisada t12))


		(= (dificultat t1) 1)
        (= (dificultat t2) 2)
        (= (dificultat t3) 3)
        (= (dificultat t4) 2)
        (= (dificultat t5) 3)
        (= (dificultat t6) 1)
        (= (dificultat t7) 1)
        (= (dificultat t8) 2)
        (= (dificultat t9) 3)
        (= (dificultat t10) 2)
        (= (dificultat t11) 3)
        (= (dificultat t12) 1)

        (= (temps t1) 3)
        (= (temps t2) 3)
        (= (temps t3) 3)
        (= (temps t4) 3)
        (= (temps t5) 3)
        (= (temps t6) 3)
        (= (temps t7) 3)
        (= (temps t8) 3)
        (= (temps t9) 3)
        (= (temps t10) 3)
        (= (temps t11) 3)
        (= (temps t12) 3)

        (= (tempsTotal) 0)

    )
    (:goal
        (forall (?t - tasca) (revisada ?t))
    )

    (:metric minimize (tempsTotal))
)